<html>
    <body>
        <h1><?php echo($str);?>&nbsp;&nbsp;<a>:<span>(</span></a></h1>
        <div id='au'><h5>ss框架&nbsp;&nbsp;火子集工作室强力驱动 &reg;2014-09</h5></div>
    </body>
</html>
<style>
    *{
        margin:0px;
        padding:0px;
    }
    h1{
        font-weight:normal;
        color:red;
        margin-top:100px;
        margin-left:100px;
    }
    #au{
        position:absolute;
        top:90%;
        left:40%;
    }
    a{
        font-size:80px;
    }
    span{
        position:relative;
        top:7px;
        left:-10px;
    }
</style>